### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by OckhamOdyssey** [JamieCruwys/bash-menu-generator#3]
Every time I try to run the example the following problem always appears:
```
./menu.sh: 16: ./menu.sh: Syntax error: "(" unexpected
```
I have noticed that this appears because the terminal tries to execute the script with sh, which doesn't allow some expressions, and not with bash. To solve it I think the best thing would be to change the first line of menu.sh to ``` #!/bin/bash ```

**Comment by jamiescode** [comment]
Fixed in db955f1
